/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './about.component';
const styles_AboutComponent:any[] = ([] as any[]);
export const RenderType_AboutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AboutComponent,data:{}});
export function View_AboutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),11,'div',[['class','container']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),
      i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      7,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','col-md-12']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['세상에 하나밖에 없는 나의 업을 찾아보세요!'])),(_l()(),i0.ɵted((null as any),['\n        '])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n']))],
      (null as any),(null as any));
}
export function View_AboutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-about',([] as any[]),
      (null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent)),
      i0.ɵdid(49152,(null as any),0,i1.AboutComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AboutComponentNgFactory:i0.ComponentFactory<i1.AboutComponent> = i0.ɵccf('app-about',
    i1.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9UcmluaXR5L1Byb2plY3RzL0ZpbmRVcC9hc3NldHMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMuQWJvdXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcclxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPCEtLTxkaXYgY2xhc3M9XCJyb3dcIj5cclxuICAgICAgPGRpdiBjbGFzcz1cImNvbC1tZC0xMlwiPlxyXG4gICAgICAgIDxpbWcgW3NyY109XCJodHRwOi8veW91cmRvc3QtYmxvZy1pbWFnZXMuczMtYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxNi8wMi8yMzIwNTQyMS9jcmVhdGl2ZS1jb21wcmVzc29yLTEuanBnXCIgY2xhc3M9XCJpbWctcmVzcG9uc2l2ZVwiIGFsdD1cIm1haW4gaW1hZ2VcIj5cclxuICAgICAgPC9kaXY+XHJcbiAgICA8L2Rpdj4tLT5cclxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cclxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTEyXCI+XHJcbiAgICAgICAgICAgIDxoMz7shLjsg4Hsl5Ag7ZWY64KY67CW7JeQIOyXhuuKlCDrgpjsnZgg7JeF7J2EIOywvuyVhOuztOyEuOyalCE8L2gzPlxyXG4gICAgICAgIDwvZGl2PlxyXG4gICAgPC9kaXY+XHJcbjwvZGl2PiIsIjxhcHAtYWJvdXQ+PC9hcHAtYWJvdXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsdUNBQ0E7TUFBQTtNQUFBLDhCQUF1QiwyQ0FLVjthQUFBLDRCQUNUO01BQUE7TUFBQSxnQkFBaUIsK0NBQ2I7TUFBQTtNQUFBLDRDQUF1QjtNQUNuQjtVQUFBLDBEQUFJO1VBQUEsK0JBQTZCO01BQy9CLDJDQUNKOzs7O29CQ1hWO01BQUE7YUFBQTtVQUFBOzs7In0=
