/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './interest-input.component.ngfactory';
import * as i2 from './interest-input.component';
import * as i3 from './interest.service';
import * as i4 from './interest-list.component.ngfactory';
import * as i5 from './interest-list.component';
import * as i6 from './interests.component';
const styles_InterestsComponent:any[] = ([] as any[]);
export const RenderType_InterestsComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_InterestsComponent,data:{}});
export function View_InterestsComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','row']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-interest-input',([] as any[]),
          (null as any),(null as any),(null as any),i1.View_InterestInputComponent_0,
          i1.RenderType_InterestInputComponent)),i0.ɵdid(114688,(null as any),0,i2.InterestInputComponent,
          [i3.InterestService],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
          'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'app-interest-list',([] as any[]),(null as any),(null as any),
          (null as any),i4.View_InterestListComponent_0,i4.RenderType_InterestListComponent)),
      i0.ɵdid(114688,(null as any),0,i5.InterestListComponent,[i3.InterestService],
          (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    _ck(_v,4,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_InterestsComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-interests',
      ([] as any[]),(null as any),(null as any),(null as any),View_InterestsComponent_0,
      RenderType_InterestsComponent)),i0.ɵdid(49152,(null as any),0,i6.InterestsComponent,
      [i3.InterestService],(null as any),(null as any))],(null as any),(null as any));
}
export const InterestsComponentNgFactory:i0.ComponentFactory<i6.InterestsComponent> = i0.ɵccf('app-interests',
    i6.InterestsComponent,View_InterestsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9pbnRlcmVzdHMvaW50ZXJlc3RzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9UcmluaXR5L1Byb2plY3RzL0ZpbmRVcC9hc3NldHMvYXBwL2ludGVyZXN0cy9pbnRlcmVzdHMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9pbnRlcmVzdHMvaW50ZXJlc3RzLmNvbXBvbmVudC50cy5JbnRlcmVzdHNDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvUHJvamVjdHMvRmluZFVwL2Fzc2V0cy9hcHAvaW50ZXJlc3RzL2ludGVyZXN0cy5jb21wb25lbnQudHMuSW50ZXJlc3RzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxhcHAtaW50ZXJlc3QtaW5wdXQ+PC9hcHAtaW50ZXJlc3QtaW5wdXQ+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8aHI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxhcHAtaW50ZXJlc3QtbGlzdD48L2FwcC1pbnRlcmVzdC1saXN0PlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLWludGVyZXN0cz48L2FwcC1pbnRlcmVzdHM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSwrQ0FDUTtNQUFBO01BQUEsNENBQWlCO01BQ2I7VUFBQTs4Q0FBQSxVQUFBO1VBQUEsa0RBQXlDO1VBQUEsaUJBQ3ZDLCtDQUNOO2lCQUFBO2NBQUEsMERBQUk7VUFBQSxpQkFDSjtVQUFBO01BQWlCLG1EQUNiO1VBQUE7VUFBQTthQUFBO1VBQUEsNkJBQXVDO01BQ3JDO0lBTEY7SUFJQTs7OztvQkNOWjtNQUFBO21DQUFBLFVBQUE7TUFBQTs7OyJ9
