/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './interest.component.ngfactory';
import * as i2 from './interest.component';
import * as i3 from './interest.service';
import * as i4 from '@angular/common';
import * as i5 from './interest-list.component';
const styles_InterestListComponent:any[] = ([] as any[]);
export const RenderType_InterestListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_InterestListComponent,data:{}});
function View_InterestListComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'app-interest',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_InterestComponent_0,
      i1.RenderType_InterestComponent)),i0.ɵdid(49152,(null as any),0,i2.InterestComponent,
      [i3.InterestService],{interest:[0,'interest']},(null as any)),(_l()(),i0.ɵted((null as any),
      ['\n            ']))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_InterestListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      [' \n            '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,
      (null as any),View_InterestListComponent_1)),i0.ɵdid(802816,(null as any),0,
      i4.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,
          'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),[' \n        '])),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i5.InterestListComponent = _v.component;
    const currVal_0:any = _co.interests;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_InterestListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-interest-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_InterestListComponent_0,
      RenderType_InterestListComponent)),i0.ɵdid(114688,(null as any),0,i5.InterestListComponent,
      [i3.InterestService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const InterestListComponentNgFactory:i0.ComponentFactory<i5.InterestListComponent> = i0.ɵccf('app-interest-list',
    i5.InterestListComponent,View_InterestListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9pbnRlcmVzdHMvaW50ZXJlc3QtbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9pbnRlcmVzdHMvaW50ZXJlc3QtbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9UcmluaXR5L1Byb2plY3RzL0ZpbmRVcC9hc3NldHMvYXBwL2ludGVyZXN0cy9pbnRlcmVzdC1saXN0LmNvbXBvbmVudC50cy5JbnRlcmVzdExpc3RDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvUHJvamVjdHMvRmluZFVwL2Fzc2V0cy9hcHAvaW50ZXJlc3RzL2ludGVyZXN0LWxpc3QuY29tcG9uZW50LnRzLkludGVyZXN0TGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+IFxuICAgICAgICAgICAgPGFwcC1pbnRlcmVzdCBcbiAgICAgICAgICAgICAgICBbaW50ZXJlc3RdPVwiaW50ZXJlc3RcIiBcbiAgICAgICAgICAgICAgICAqbmdGb3I9XCJsZXQgaW50ZXJlc3Qgb2YgaW50ZXJlc3RzXCI+XG4gICAgICAgICAgICA8L2FwcC1pbnRlcmVzdD4gXG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtaW50ZXJlc3QtbGlzdD48L2FwcC1pbnRlcmVzdC1saXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNFWTtNQUFBO3FDQUFBLFVBQUE7TUFBQSw4REFFdUM7TUFBQTtJQURuQztJQURKLFdBQ0ksU0FESjs7OztvQkFGWiwrQ0FDUTtNQUFBO01BQUEsMERBQXNDO01BQUEsc0JBQ2xDO01BQUEsb0RBQUE7aUJBQUE7VUFBQSwyQkFHZTtNQUNiOztJQUZFO0lBRkosV0FFSSxTQUZKOzs7O29CQ0ZaO01BQUE7c0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
