/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header.component.ngfactory';
import * as i3 from './header.component';
import * as i4 from './auth/auth.service';
import * as i5 from '@angular/router';
import * as i6 from './interests/interest.service';
import * as i7 from './_directives/alert.component.ngfactory';
import * as i8 from './_directives/alert.component';
import * as i9 from './_services/alert.service';
import * as i10 from '@angular/http';
import * as i11 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_HeaderComponent_0,i2.RenderType_HeaderComponent)),
      i1.ɵdid(49152,(null as any),0,i3.HeaderComponent,[i4.AuthService,i5.Router,i6.InterestService],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',
          ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i5.RouterOutlet,[i5.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'alert',([] as any[]),(null as any),(null as any),
          (null as any),i7.View_AlertComponent_0,i7.RenderType_AlertComponent)),i1.ɵdid(114688,
          (null as any),0,i8.AlertComponent,[i9.AlertService],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,6,0);
    _ck(_v,9,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵprd(4608,(null as any),i6.InterestService,i6.InterestService,[i10.Http]),
      i1.ɵdid(49152,(null as any),0,i11.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i11.AppComponent> = i1.ɵccf('my-app',
    i11.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvUHJvamVjdHMvRmluZFVwL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvUHJvamVjdHMvRmluZFVwL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9Qcm9qZWN0cy9GaW5kVXAvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhcHAtaGVhZGVyPjwvYXBwLWhlYWRlcj5cclxuPGhyPlxyXG48cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbjxhbGVydD48L2FsZXJ0PlxyXG4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQSw2QkFBeUIsdUNBQ3pCO2lCQUFBO2NBQUEsMERBQUk7VUFBQSxTQUNKO1VBQUE7YUFBQTtzQ0FBQTtVQUFBLGVBQStCLHVDQUMvQjtVQUFBO1VBQUEsNkVBQUE7VUFBQTtNQUFlO0lBRGY7SUFDQTs7OztvQkNIQTtNQUFBO2FBQUE7YUFBQTs7OzsifQ==
